import { baseConfig } from '@conecta/eslint-config/base';

/** @type {import("eslint").Linter.Config[]} */
export default [
  {
    // `next-env.d.ts` is generated by Next.js and must not be edited.
    ignores: ['next-env.d.ts'],
  },
  ...baseConfig,
  {
    // Next.js App Router requires default exports for route segment files
    // (page/layout/route/error/not-found/loading), and next-intl's
    // `getRequestConfig` requires a default export from src/i18n/request.ts,
    // so disable the shared base config's `import/no-default-export` here.
    files: ['src/app/**/*.{ts,tsx}', 'src/i18n/request.ts'],
    rules: {
      'import/no-default-export': 'off',
    },
  },
];
