import { baseConfig } from '@conecta/eslint-config/base';

/** @type {import("eslint").Linter.Config[]} */
export default [
  {
    // `next-env.d.ts` is generated by Next.js and must not be edited.
    ignores: ['next-env.d.ts'],
  },
  ...baseConfig,
  {
    // Next.js App Router requires default exports for route segment files
    // (page/layout/route/error/not-found/loading), so disable the shared
    // base config's `import/no-default-export` warning under `src/app/`.
    files: ['src/app/**/*.{ts,tsx}'],
    rules: {
      'import/no-default-export': 'off',
    },
  },
];
