// Maps each system role key to the permission keys it should have.
export const ROLE_PERMISSIONS: Record<string, string[]> = {
  ADMIN: [
    // All permissions — ADMIN gets everything
    'organization:read', 'organization:update',
    'school:create', 'school:read', 'school:update', 'school:delete',
    'modality:create', 'modality:read', 'modality:update', 'modality:delete',
    'school-modality:create', 'school-modality:read', 'school-modality:update', 'school-modality:delete',
    'class:create', 'class:read', 'class:update', 'class:delete', 'class:assign-coach',
    'user:create', 'user:read', 'user:update', 'user:delete', 'user:invite', 'user:impersonate',
    'role:read', 'role:assign',
    'student:create', 'student:read', 'student:update', 'student:delete', 'student:export', 'student:anonymize',
    'guardian:create', 'guardian:read', 'guardian:update', 'guardian:delete',
    'enrollment:create', 'enrollment:read', 'enrollment:update', 'enrollment:cancel',
    'attendance:create', 'attendance:read',
    'invoice:create', 'invoice:read', 'invoice:cancel', 'invoice:refund',
    'payment:create', 'payment:read', 'payment:refund',
    'subscription:read', 'subscription:pause', 'subscription:cancel',
    'notification:create', 'notification:read', 'notification:delete',
    'report:read', 'report:export',
    'audit:read',
    'settings:read', 'settings:update',
    'brand:read', 'brand:update',
    'payment-gateway:read', 'payment-gateway:connect', 'payment-gateway:disconnect',
  ],
  ORG_STAFF: [
    'organization:read',
    'school:read', 'school:update',
    'modality:create', 'modality:read', 'modality:update', 'modality:delete',
    'school-modality:create', 'school-modality:read', 'school-modality:update', 'school-modality:delete',
    'class:create', 'class:read', 'class:update', 'class:assign-coach',
    'user:create', 'user:read', 'user:update', 'user:invite',
    'role:read', 'role:assign',
    'student:create', 'student:read', 'student:update', 'student:delete', 'student:export',
    'guardian:create', 'guardian:read', 'guardian:update', 'guardian:delete',
    'enrollment:create', 'enrollment:read', 'enrollment:update', 'enrollment:cancel',
    'attendance:create', 'attendance:read',
    'invoice:create', 'invoice:read', 'invoice:cancel',
    'payment:create', 'payment:read',
    'subscription:read', 'subscription:pause', 'subscription:cancel',
    'notification:create', 'notification:read', 'notification:delete',
    'report:read', 'report:export',
    'audit:read',
    'settings:read',
    'brand:read',
    'payment-gateway:read',
  ],
  SCHOOL_STAFF: [
    'school:read.own-school',
    'school-modality:create.own-school', 'school-modality:read.own-school',
    'school-modality:update.own-school', 'school-modality:delete.own-school',
    'class:create.own-school', 'class:read.own-school', 'class:update.own-school',
    'class:delete.own-school', 'class:assign-coach.own-school',
    'user:read.own-school', 'user:invite',
    'student:create.own-school', 'student:read.own-school', 'student:update.own-school',
    'student:delete.own-school', 'student:export',
    'guardian:create.own-school', 'guardian:read.own-school', 'guardian:update.own-school',
    'enrollment:create.own-school', 'enrollment:read.own-school',
    'enrollment:update.own-school', 'enrollment:cancel.own-school',
    'attendance:create.own-school', 'attendance:read.own-school',
    'invoice:create.own-school', 'invoice:read.own-school', 'invoice:cancel.own-school',
    'payment:create.own-school', 'payment:read.own-school',
    'subscription:read.own-school', 'subscription:pause.own-school', 'subscription:cancel.own-school',
    'notification:create', 'notification:read',
    'report:read.own-school',
    'audit:read.own-school',
    'settings:read',
  ],
  COACH: [
    'class:read.own',
    'student:read.own-school',
    'attendance:create.own-class', 'attendance:read.own-school',
    'notification:create', 'notification:read',
  ],
  GUARDIAN: [
    'student:read.own', 'student:update.own',
    'guardian:read.own', 'guardian:update.own',
    'enrollment:read.own',
    'attendance:read.own',
    'invoice:read.own',
    'payment:read.own',
    'notification:read',
  ],
};

export const SYSTEM_ROLES = [
  { key: 'ADMIN', name: 'Administrador', description: 'Acesso total à organização' },
  { key: 'ORG_STAFF', name: 'Operacional (rede)', description: 'Operações do dia-a-dia em toda a organização' },
  { key: 'SCHOOL_STAFF', name: 'Operacional (unidade)', description: 'Operações restritas às unidades atribuídas' },
  { key: 'COACH', name: 'Professor', description: 'Acesso às turmas que leciona' },
  { key: 'GUARDIAN', name: 'Responsável', description: 'Acesso aos dados dos próprios dependentes' },
];
